# Copyright (c) 2015 The Regents of the University of Michigan.
# All Rights Reserved.
# Licensed according to the terms of the Revised BSD License
# See LICENSE.md for details.

# These descriptions can be used to determine your production
# settings.
development:
  # The namespace of your node
  local_namespace: hathi

  # The api_root of your node, without the version stanza
  local_api_root: http://127.0.0.1

  # Where to save temporary downloaded files.
  # If you are not using the included dpn-server replication
  # client, this setting does nothing.
  staging_dir: <%= Rails.root.join("dpnrepo", "staging").to_s %>

  # Where to save stored files for preservation.
  # If you are not using the included dpn-server replication
  # client, this setting does nothing.
  repo_dir: <%= Rails.root.join("dpnrepo", "preservation").to_s %>

  # The background queue adapter to use.  dpn-server is
  # configured to work with Resque, which is based on Redis.
  #
  # You can also set this to :disabled, which will disable
  # the synchronization and replication clients.
  # queue_adapter: :disabled
  queue_adapter: :resque

test:
  local_namespace: hathi
  local_api_root: http://127.0.0.1
  staging_dir: <%= File.join "/tmp", "dpnrepo", "staging" %>
  repo_dir: <%= File.join "/tmp", "dpnrepo", "preservation" %>
  queue_adapter: :test

# We call to_h here for now because YAML converts Ettin::Options
# objects straight to nil, silently.
production:
  local_namespace: <%= DPN.config.dpn&.local_namespace %>
  local_api_root: <%= DPN.config.dpn&.local_api_root %>
  staging_dir: <%= DPN.config.dpn&.staging_dir %>
  repo_dir: <%= DPN.config.dpn&.repo_dir %>
  queue_adapter: <%= DPN.config.dpn&.queue_adapter %>

