development: &development
  sync: 1
  "repl_scheduler, repl_fixity, repl_validate, repl_received_notify,repl_stored_notify,repl_retrieval,repl_unpack,repl_store": 1

test:
  <<: *development

production: <%= DPN.config.resque_pool.to_h %>

