# Copyright (c) 2015 The Regents of the University of Michigan.
# All Rights Reserved.
# Licensed according to the terms of the Revised BSD License
# See LICENSE.md for details.

# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &default
  salt: <%= AppSettings.secrets.salt %>
  cipher_key: <%= AppSettings.secrets.cipher_key %>
  cipher_iv: <%= AppSettings.secrets.cipher_iv %>
  transfer_private_key: <%= AppSettings.secrets.transfer_private_key %>
  secret_key_base: <%= AppSettings.secrets.secret_key_base %>

production:
  <<: *default
development:
  <<: *default
test:
  <<: *default

impersonate_aptrust:
  <<: *default
impersonate_chron:
  <<: *default
impersonate_hathi:
  <<: *default
impersonate_sdr:
  <<: *default
impersonate_tdr:
  <<: *default
