dpn:
  local_namespace: hathi
  local_api_root: http://127.0.0.1
  staging_dir: <%= Rails.root.join("dpnrepo", "staging").to_s %>
  repo_dir: <%= Rails.root.join("dpnrepo", "preservation").to_s %>
  queue_adapter: :resque

resque_pool:
  sync: 1
  repl: 1

redis:
  host: localhost
  port: 6379

secrets:
  salt: "development_salt"
  cipher_key: "foMXggnM3xLHatbSP0ZXW6ThZXOXqp8ImyaJQ/0Jlqo=\n"
  cipher_iv: "L213BeYaK4QDG8krUaCYnA==\n"
  transfer_private_key: "/l/home/dpnadm/.ssh/hathi.key"
  secret_key_base: 2ea1fbd4ac4699fd0e31096b51ef545b482d9ad4bd40ca7a07276a6712e45dccb821a88bc2adc09793b0ddc2be19e16068c48286ab659aad7807a8e5c1b32c3a
