dpn:
  local_namespace: hathi
  local_api_root: http://127.0.0.1
  staging_dir: <%= File.join "/tmp", "dpnrepo", "staging" %>
  repo_dir: <%= File.join "/tmp", "dpnrepo", "preservation" %>
  queue_adapter: :test

resque_pool:
  sync: 1
  repl: 1

redis:
  host: localhost
  port: 6379

secrets:
  salt: "test_salt"
  cipher_key: "foMXggnM3xLHatbSP0ZXW6ThZXOXqp8ImyaJQ/0Jlqo=\n"
  cipher_iv: "L213BeYaK4QDG8krUaCYnA==\n"
  transfer_private_key: "/l/home/dpnadm/.ssh/hathi.key"
  secret_key_base: 525e7a0e528c0972699d038ef6a5eb35c493cd6db6db85baf0bf756ba59aeb50a2f5bd38b421d61cc99683df3da779048ec615a5fd72e62c65a86f3f71edcc25
